-- Defines
NDefines.NGame.END_DATE = "1952.1.1.1"
NDefines.NGame.MAJOR_PARTICIPANTS_FOR_MAJOR_WAR = 4

NDefines.NDiplomacy.MAX_OPINION_VALUE = 200
NDefines.NDiplomacy.MIN_OPINION_VALUE = -200
NDefines.NDiplomacy.VERY_GOOD_OPINION = 75
NDefines.NDiplomacy.VERY_BAD_OPINION = -75
NDefines.NDiplomacy.TENSION_CIVIL_WAR_IMPACT = 0.15
NDefines.NDiplomacy.TENSION_NO_CB_WAR = 15
NDefines.NDiplomacy.TENSION_CB_WAR = 10
NDefines.NDiplomacy.TENSION_PUPPET = 1.5
NDefines.NDiplomacy.TENSION_TIME_SCALE_MONTHLY_FACTOR = 0.007

NDefines.NCountry.LOCAL_MANPOWER_ACCESSIBLE_NON_CORE_FACTOR = 0.1
NDefines.NCountry.MAJOR_MIN_FACTORIES = 42
NDefines.NCountry.POLITICAL_POWER_CAP = 1000.0

NDefines.NBuildings.MAX_SHARED_SLOTS = 30

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 750
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 750
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 750

NDefines.NAI.MAX_DISTANCE_NALAV_INVASION = 250.0

-- Graphics
NDefines_Graphics.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 2048
NDefines_Graphics.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 512
NDefines_Graphics.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 8196
NDefines_Graphics.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 24000
NDefines_Graphics.NGraphics.VICTORY_POINT_MAP_ICON_TEXT_CUTOFF = {200, 400, 700}



